spring:
  application:
    name: spring-jpa-partition

  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      minimum-idle: 0
      maximum-pool-size: 5
      idle-timeout: 30000
      max-lifetime: 60000
      keepalive-time: 30000
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: true
